INSERT INTO Artists (Name, Country) VALUES ('The Beatles', 'United Kingdom');
INSERT INTO Artists (Name, Country) VALUES ('ABBA', 'Sweden');
INSERT INTO Artists (Name, Country) VALUES ('Pink Floyd', 'United Kingdom');
INSERT INTO Artists (Name, Country) VALUES ('Led Zeppelin', 'United Kingdom');
INSERT INTO Artists (Name, Country) VALUES ('Queen', 'United Kingdom');
INSERT INTO Albums (Title, ReleaseYear, ArtistId) VALUES ('Abbey Road', 1969, 1);
INSERT INTO Albums (Title, ReleaseYear, ArtistId) VALUES ('Let It Be', 1970, 1);
INSERT INTO Albums (Title, ReleaseYear, ArtistId) VALUES ('Arrival', 1976, 2);
INSERT INTO Albums (Title, ReleaseYear, ArtistId) VALUES ('The Dark Side of the Moon', 1973, 3);
INSERT INTO Albums (Title, ReleaseYear, ArtistId) VALUES ('Led Zeppelin IV', 1971, 4);
INSERT INTO Albums (Title, ReleaseYear, ArtistId) VALUES ('A Night at the Opera', 1975, 5);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Come Together', 259, 1);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Something', 182, 1);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Here Comes the Sun', 185, 1);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Let It Be', 243, 2);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Get Back', 189, 2);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Come Together', 259, 1);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Something', 182, 1);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Here Comes the Sun', 185, 1);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Let It Be', 243, 2);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Get Back', 189, 2);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Dancing Queen', 230, 3);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Money, Money, Money', 185, 3);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Stairway to Heaven', 482, 5);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Black Dog', 294, 5);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Bohemian Rhapsody', 354, 6);
INSERT INTO Tracks (Title, Duration, AlbumId) VALUES ('Love of My Life', 218, 6);
